### ISSUE TITLE
Can't find application path for '/usr/local/bin/studio' each time I restart the MacBook

### ISSUE THREAD

**Issue by DanielSchreurs** [bchatard/jetbrains-alfred-workflow#46]
Q | A
--- | ---
Workflow version | _2.0.0_
OSX Version | _10.10.5 / 10.11.05_
Alfred Version | _3_
JetBrains Product/Version | _PhpStorm / 2016.1.1_
Installation type | _classic .dmg / Caskroom / JB Toolbox_

### Description

[2018-10-24 08:17:02][input.scriptfilter] Queuing argument ''
[2018-10-24 08:17:02][input.scriptfilter] Script with argument '(null)' finished
[2018-10-24 08:17:02][input.scriptfilter] {"items":[{"uid":"e_0","title":"Can't find application path for '\/usr\/local\/bin\/clion'","subtitle":"Please enable log and contact developer","match":null,"arg":"","icon":{"path":"\/System\/Library\/CoreServices\/CoreTypes.bundle\/Contents\/Resources\/AlertStopIcon.icns"},"valid":false,"autocomplete":"","type":"default","mods":null,"text":{"copy":"#0 \/Users\/danielschreurs\/Library\/Application Support\/Alfred 3\/Alfred.alfredpreferences\/workflows\/user.workflow.B8C96E8F-D00C-403A-B8E4-5A1D7DCFDFAE\/Project.php(108): Project->checkJetbrainsApp()\n#1 Command line code(4): Project->search('')\n#2 {main}"},"quicklookurl":null,"variables":[]}],"variables":[]}
[2018-10-24 08:17:10][input.scriptfilter] Queuing argument ''
[2018-10-24 08:17:10][input.scriptfilter] Script with argument '(null)' finished
[2018-10-24 08:17:10][input.scriptfilter] {"items":[{"uid":"e_0","title":"Can't find application path for '\/usr\/local\/bin\/idea'","subtitle":"Please enable log and contact developer","match":null,"arg":"","icon":{"path":"\/System\/Library\/CoreServices\/CoreTypes.bundle\/Contents\/Resources\/AlertStopIcon.icns"},"valid":false,"autocomplete":"","type":"default","mods":null,"text":{"copy":"#0 \/Users\/danielschreurs\/Library\/Application Support\/Alfred 3\/Alfred.alfredpreferences\/workflows\/user.workflow.B8C96E8F-D00C-403A-B8E4-5A1D7DCFDFAE\/Project.php(108): Project->checkJetbrainsApp()\n#1 Command line code(4): Project->search('')\n#2 {main}"},"quicklookurl":null,"variables":[]}],"variables":[]}
### Step to reproduce
...

**Comment by bchatard** [comment]
Hi @DanielSchreurs 

can you take a look on issue #45?
Can you check the path of `RUN_PATH` in `/usr/local/bin/studio`? There is any change between each restart?

Thanks,

**Comment by bchatard** [comment]
maybe related to #48

**Comment by tofagerl** [comment]
@bchatard It's a python script, so I can only understand parts of it, but the paths are as follows: 
```
12   │ RUN_PATH = u'/Applications/IntelliJ IDEA.app'
13   │ CONFIG_PATH = u'/Users/tom/Library/Preferences/IntelliJIdea2018.3'
14   │ SYSTEM_PATH = u'/Users/tom/Library/Caches/IntelliJIdea2018.3'
```

CONFIG_PATH and SYSTEM_PATH are fine, but RUN_PATH points to nothing. The correct path would be `$HOME/Applications/JetBrains\ Toolbox/IntelliJ\ IDEA\ Ultimate.app` in my case.

**Comment by bchatard** [comment]
@tofagerl 

- [ ] Can you update this path: [Create command line launcher](https://github.com/bchatard/jetbrains-alfred-workflow#create-command-line-launcher)
- [ ] The path is it correct after?
- [ ] Can you restart, and check the path again?
- [ ] Did you use "shell generation" from Toolbox?

**Comment by tofagerl** [comment]
@bchatard Yes, the path is correct after. Including after restart. I wonder if that command line launcher will be overwritten once I upgrade to the next version, though, since it's hard coded the application version in the path.
I did enable shell generation from toolbox, but it seems like it does nothing. Even after I deleted the script and uninstalled/reinstalled multiple times, there was no script at the path.

**Comment by bchatard** [comment]
@tofagerl 
Yes you need to update the command line launcher after each update.

For now I have an issue when using "shell script generation" from Toolbox

**Comment by tofagerl** [comment]
@bchatard  Yeah, this is the old launcher from the app itself - I for some reason can't get the toolbox launcher to install, which means that I'm failing to get the launcher to fail ;)
